### ISSUE TITLE
excell表格聚焦

### ISSUE THREAD

**Issue by wangjun043179** [xuliangzhan/vue-element-extends#40]
就是我看网页案例的时候，excell选中当前单元格有边框，而且浏览器控制台审查元素当前行也是input，然后我使用代码的时候，就没有选中效果，而且也不是input，询问下怎么解决

**Comment by wangjun043179** [comment]
就是我选中某一单元格没有突出样式，我看案例选中都有附带当前单元格边框的

**Comment by xuliangzhan** [comment]
样式需要自己去实现，demo可以参考

**Comment by wangjun043179** [comment]
但是我看文档中写了某单元格聚焦，我加了不起作用，而且我是参照demo的代码，但是你们得demo在网页中有效果，直接用代码也不出效果，就是单元格聚焦的效果，不知道为什么

**Comment by xuliangzhan** [comment]
最好提供下能重现的[问题链接](https://jsrun.net/zTXKp/edit)或调用代码

**Comment by wangjun043179** [comment]
![TIM截图20190330125531](https://user-images.githubusercontent.com/44045271/55271652-429eb400-52eb-11e9-8b25-afbe4e229ecc.png)
![TIM截图20190330125547](https://user-images.githubusercontent.com/44045271/55271654-47fbfe80-52eb-11e9-8cb0-22637c0c13a5.png)

**Comment by wangjun043179** [comment]
就像demo中的单元格聚焦，我直接是参考excell4改的，但是刚开始还没改，直接放进去就没聚焦效果

**Comment by wangjun043179** [comment]
会不会是和element ui的样式冲突？因为我是把它作为子组件引入到pages的，但是父组件中还有element ui的样式

**Comment by xuliangzhan** [comment]
你指的事输入框没有聚焦还是没有聚焦的边框样式？
如果是聚焦边框样式，你可以参考excel4 demo，通过覆盖实现边框效果，你可以在公共样式文件去覆盖就行
```css
.excel-table4 .el-table__body .el-table__row>td.editable-col_checked {
  border: 1px solid #217346;
}
.excel-table4 .el-table__body .el-table__row>td .cell .el-input__inner {
  border-color: #217346;
}
```
